#!/usr/bin/env bash

  # Configuration
  HOST_NAME="localhost"
  USER="postgres"
  PORT="5432"
  BACKUP_DIR="/home/radhe/work/dbbkups"
  DATE=$(date +"%Y%m%d_%H%M%S")
  LOG_FILE="/home/radhe/work/shell/logs"

  # Get list of databases (excluding templates)
  DATABASES=$(psql -h "$HOST_NAME" -p "$PORT" -U "$USER" -d postgres -t -c "SELECT datname FROM pg_database WHERE datistemplate = false;")

  #Ensure backup Directory Exist
  mkdir -p "$BACKUP_DIR"
  touch "$LOG_FILE"

  log() {
      echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG_FILE"
  }

  log "Starting backup..."
  for DB in $DATABASES; do
    DB=$(echo "$DB" | xargs)
    BACKUP_FILE="$BACKUP_DIR/${DB}_${DATE}.sql.gz"

    log " ==== Taking Backup of : $DB ==== "
    if pg_dump -h "${HOST_NAME}" -p "${PORT}" -U "${USER}" "${DB}" | gzip > "${BACKUP_FILE}" ; then
        log "✅ Success: $DB"
    else
          log "❌ Failed to back up database: $DB"
    fi
  done
  log "All backups complete."